services:
  postgres:
    image: postgres:17
    container_name: autotracker-postgres
    environment:
      POSTGRES_DB: autotrackerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - autotracker_postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend/AutoTracker.Api
      dockerfile: Dockerfile
    container_name: autotracker-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=autotrackerdb;Username=postgres;Password=postgres"
      Frontend__BaseUrl: "http://localhost:5173"
      MailSettings__Host: "sandbox.smtp.mailtrap.io"
      MailSettings__Port: "2525"
      MailSettings__Email: "0a0bd94e873298"
      MailSettings__Password: "1e419ca8e1f82c"
      


volumes:
  autotracker_postgres_data: