services:
  postgres:
    image: postgres:17
    container_name: autotracker-postgres
    environment:
      POSTGRES_DB: autotrackerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - autotracker_postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend/AutoTracker.Api
      dockerfile: Dockerfile
    container_name: autotracker-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=autotrackerdb;Username=postgres;Password=postgres"
      Frontend__BaseUrl: "http://localhost:5173"
      MailSettings__Host: "smtp.gmail.com"
      MailSettings__Port: "587"
      MailSettings__Email: "${MAIL_EMAIL}"
      MailSettings__Password: "${MAIL_PASSWORD}"  
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:8080/api"
    container_name: autotracker-frontend
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  autotracker_postgres_data: