// <auto-generated />
using System;
using AutoTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619235201_AccountTransactionSnapshots")]
    partial class AccountTransactionSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoTracker.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.CustomerVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChassisNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentMileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceBusinessId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceCustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceBusinessId");

                    b.HasIndex("ServiceCustomerId");

                    b.ToTable("CustomerVehicles");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceAccountTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CustomerVehicleId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlateSnapshot")
                        .HasColumnType("text");

                    b.Property<int>("ServiceBusinessId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceCustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceWorkOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceTitle")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleSnapshot")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerVehicleId");

                    b.HasIndex("ServiceBusinessId");

                    b.HasIndex("ServiceCustomerId");

                    b.HasIndex("ServiceWorkOrderId");

                    b.ToTable("ServiceAccountTransactions");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceBusiness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("ServiceBusinesses");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceBusinessId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceBusinessId");

                    b.ToTable("ServiceCustomers");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("boolean");

                    b.Property<int>("ServiceBusinessId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceBusinessId");

                    b.ToTable("ServiceNotes");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServicePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("ServiceBusinessId")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceBusinessId");

                    b.ToTable("ServiceParts");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServicePartSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("ServiceBusinessId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicePartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ServiceBusinessId");

                    b.HasIndex("ServicePartId");

                    b.ToTable("ServicePartSales");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceWorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerVehicleId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("numeric");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<decimal>("PartsCost")
                        .HasColumnType("numeric");

                    b.Property<int>("ServiceBusinessId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerVehicleId");

                    b.HasIndex("ServiceBusinessId");

                    b.ToTable("ServiceWorkOrders");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentMileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.VehicleNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleNotes");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.VehicleReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleReminders");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.CustomerVehicle", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.ServiceBusiness", "ServiceBusiness")
                        .WithMany("CustomerVehicles")
                        .HasForeignKey("ServiceBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTracker.Api.Models.ServiceCustomer", "ServiceCustomer")
                        .WithMany("Vehicles")
                        .HasForeignKey("ServiceCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceBusiness");

                    b.Navigation("ServiceCustomer");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceAccountTransaction", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.CustomerVehicle", "CustomerVehicle")
                        .WithMany()
                        .HasForeignKey("CustomerVehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AutoTracker.Api.Models.ServiceBusiness", "ServiceBusiness")
                        .WithMany()
                        .HasForeignKey("ServiceBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTracker.Api.Models.ServiceCustomer", "ServiceCustomer")
                        .WithMany()
                        .HasForeignKey("ServiceCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTracker.Api.Models.ServiceWorkOrder", "ServiceWorkOrder")
                        .WithMany()
                        .HasForeignKey("ServiceWorkOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomerVehicle");

                    b.Navigation("ServiceBusiness");

                    b.Navigation("ServiceCustomer");

                    b.Navigation("ServiceWorkOrder");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceBusiness", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.AppUser", "OwnerUser")
                        .WithOne("ServiceBusiness")
                        .HasForeignKey("AutoTracker.Api.Models.ServiceBusiness", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceCustomer", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.ServiceBusiness", "ServiceBusiness")
                        .WithMany("Customers")
                        .HasForeignKey("ServiceBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceBusiness");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceNote", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.ServiceBusiness", "ServiceBusiness")
                        .WithMany("Notes")
                        .HasForeignKey("ServiceBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceBusiness");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServicePart", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.ServiceBusiness", "ServiceBusiness")
                        .WithMany("Parts")
                        .HasForeignKey("ServiceBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceBusiness");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServicePartSale", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.ServiceBusiness", "ServiceBusiness")
                        .WithMany("PartSales")
                        .HasForeignKey("ServiceBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTracker.Api.Models.ServicePart", "ServicePart")
                        .WithMany("Sales")
                        .HasForeignKey("ServicePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceBusiness");

                    b.Navigation("ServicePart");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceWorkOrder", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.CustomerVehicle", "CustomerVehicle")
                        .WithMany("WorkOrders")
                        .HasForeignKey("CustomerVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTracker.Api.Models.ServiceBusiness", "ServiceBusiness")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ServiceBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerVehicle");

                    b.Navigation("ServiceBusiness");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.Vehicle", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.AppUser", "AppUser")
                        .WithMany("Vehicles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.VehicleNote", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.VehicleReminder", b =>
                {
                    b.HasOne("AutoTracker.Api.Models.Vehicle", "Vehicle")
                        .WithMany("Reminders")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.AppUser", b =>
                {
                    b.Navigation("ServiceBusiness");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.CustomerVehicle", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceBusiness", b =>
                {
                    b.Navigation("CustomerVehicles");

                    b.Navigation("Customers");

                    b.Navigation("Notes");

                    b.Navigation("PartSales");

                    b.Navigation("Parts");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServiceCustomer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.ServicePart", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("AutoTracker.Api.Models.Vehicle", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
